### ISSUE TITLE
启动游戏失败，'NoneType' object has no attribute 'group'，求大佬指导

### ISSUE THREAD

**Issue by VAHua** [lgc-NB2Dev/nonebot-plugin-akinator#10]
后台报错：
```
04-11 14:12:03 [ERROR] nonebot_plugin_akinator | 启动游戏失败
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\Program Files (x86)\python\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Program Files (x86)\python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_reboot\reloader.py", line 27
, in _run
    _nb_run(*args, **kwargs)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\__init__.py", line 334, in run     
    get_driver().run(*args, **kwargs)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\drivers\fastapi.py", line 186, in r
un
    uvicorn.run(
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\uvicorn\server.py", line 60, in run        
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Program Files (x86)\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Program Files (x86)\python\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\Program Files (x86)\python\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Program Files (x86)\python\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\Program Files (x86)\python\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\Program Files (x86)\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\message.py", line 476, in check_and
_run_matcher
    await _run_matcher(
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\message.py", line 428, in _run_matc
her
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\internal\matcher\matcher.py", line 
842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\internal\matcher\matcher.py", line 
817, in simple_run
    await handler(
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\dependencies\__init__.py", line 106
, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_akinator\__main__.py", line 
29, in _
    await game.start_game()
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_akinator\game.py", line 42, 
in wrapper
    return await async_func(self, *args, **kwargs)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_akinator\game.py", line 69, 
in start_game
    return await super().start_game(
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_akinator\akinator\akinator\a
sync_aki\async_akinator.py", line 192, in start_game
    region_info = await self._auto_get_region(
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_akinator\akinator\akinator\a
sync_aki\async_akinator.py", line 129, in _auto_get_region
    parsed = json.loads(match.group().split("'arrUrlThemesToPlay', ")[-1])
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by 360add** [comment]
现在就是用不了，不知道哪出问题了，作者自己的也用不了

**Comment by lgc2333** [comment]
上游库问题，有时间自己搓一个

**Comment by lgc2333** [comment]
https://github.com/lgc-NB2Dev/nonebot-plugin-akinator/releases/tag/v1.0.1
