### ISSUE TITLE
初始化游戏失败

### ISSUE THREAD

**Issue by ElainaFanBoy** [lgc-NB2Dev/nonebot-plugin-akinator#16]
请问一下初始化游戏失败是怎么回事呀
```
12-01 00:43:53 [ERROR] nonebot_plugin_akinator | Failed to start game
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\lastload\nonebot_plugin_reboot\reloader.py", line 27, in _run
    _nb_run(*args, **kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\test\nonebot_plugin_akinator\__main__.py", line 148, in _
    await aki.start()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\cooaki\akinator.py", line 169, in start
    async with self.create_client() as cli:
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\cooaki\akinator.py", line 91, in create_client
    async with AsyncClient(  # noqa: S113
TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxy'
```

**Comment by lgc2333** [comment]
请提供你环境内的httpx版本

**Comment by ElainaFanBoy** [comment]
> 请提供你环境内的httpx版本

你好，httpx版本为0.23.3

**Comment by ElainaFanBoy** [comment]
> 请提供你环境内的httpx版本

更新了一下依赖版本，现在可以了
