### ISSUE TITLE
我用不了

### ISSUE THREAD

**Issue by wuhu201314** [lgc-NB2Dev/nonebot-plugin-akinator#2]
哪里错了[ERROR] nonebot_plugin_akinator | 启动游戏失败
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "E:\test\me2\.venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "E:\test\me2\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "E:\test\me2\.venv\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "E:\test\me2\.venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\wwwwwwwwwwww\新建文件夹\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\wwwwwwwwwwww\新建文件夹\python\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\wwwwwwwwwwww\新建文件夹\python\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\wwwwwwwwwwww\新建文件夹\python\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\wwwwwwwwwwww\新建文件夹\python\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "D:\wwwwwwwwwwww\新建文件夹\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\test\me2\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "E:\test\me2\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\test\me2\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\test\me2\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "E:\test\me2\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "E:\test\me2\.venv\lib\site-packages\nonebot_plugin_akinator\__main__.py", line 35, in _
    await game.start_game()
  File "E:\test\me2\.venv\lib\site-packages\nonebot_plugin_akinator\game.py", line 42, in wrapper
    return await async_func(self, *args, **kwargs)
  File "E:\test\me2\.venv\lib\site-packages\nonebot_plugin_akinator\game.py", line 74, in start_game
    return await super().start_game(
  File "E:\test\me2\.venv\lib\site-packages\nonebot_plugin_akinator\akinator\akinator\async_aki\async_akinator.py", line
 190, in start_game
    region_info = await self._auto_get_region(
  File "E:\test\me2\.venv\lib\site-packages\nonebot_plugin_akinator\akinator\akinator\async_aki\async_akinator.py", line
 124, in _auto_get_region
    async with self.client_session.get("https://" + uri, proxy=self.proxy, ssl=False) as w:
  File "E:\test\me2\.venv\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "E:\test\me2\.venv\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "E:\test\me2\.venv\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "E:\test\me2\.venv\lib\site-packages\aiohttp\connector.py", line 899, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "E:\test\me2\.venv\lib\site-packages\aiohttp\connector.py", line 1221, in _create_proxy_connection
    proxy_req = ClientRequest(
  File "E:\test\me2\.venv\lib\site-packages\aiohttp\client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "E:\test\me2\.venv\lib\site-packages\aiohttp\client_reqrep.py", line 364, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: XXXX

**Comment by lgc2333** [comment]
看看配置

**Comment by wuhu201314** [comment]
抱歉，我不懂什么是配置

**Comment by wuhu201314** [comment]
我用的是nb-cil

**Comment by wuhu201314** [comment]
用的是自带的环境

**Comment by lgc2333** [comment]
.env

**Comment by lgc2333** [comment]
有没有动

**Comment by wuhu201314** [comment]
什么

**Comment by wuhu201314** [comment]
.env.prod吗

**Comment by wuhu201314** [comment]
我没有改

**Comment by lgc2333** [comment]
proxy设置下，挂代理

**Comment by wuhu201314** [comment]
要挂代理吗

**Comment by wuhu201314** [comment]
代理网址怎么填啊，有魔法

**Comment by lgc2333** [comment]
PROXY=HTTP代理地址

例子
```properties
PROXY=http://127.0.0.1:7890
```

**Comment by wuhu201314** [comment]
对不起，我还用不了，可能是我的问题
