### ISSUE TITLE
真寻的无法使用，已检查依赖

### ISSUE THREAD

**Issue by Nenot233** [lgc-NB2Dev/nonebot-plugin-akinator#3]
```
04-17 09:25:32 [ERROR] nonebot | Failed to import "nonebot_plugin_akinator"
Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot\bot.py", line 16, in <module>
    nonebot.load_plugins("extensive_plugin")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
 File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_akinator\__init__.py", line 3, in <module>
    from . import __main__ as __main__
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_akinator\__main__.py", line 13, in <module>
    from .akinator.akinator.exceptions import AkiNoQuestions, CantGoBackAnyFurther
ModuleNotFoundError: No module named 'extensive_plugin.nonebot_plugin_akinator.akinator.akinator'
```

**Comment by lgc2333** [comment]
子模块没克隆下来，建议使用pip安装

**Comment by Nenot233** [comment]
pip安装后还是会出现这个情况

**Comment by lgc2333** [comment]
我自己用pip安装都没问题啊

**Comment by luosheng520qaq** [comment]
使用pip我也遇到了这个问题

**Comment by luosheng520qaq** [comment]
手动pip子模块解决了
