### ISSUE TITLE
启动游戏失败

### ISSUE THREAD

**Issue by ABKQPO** [lgc-NB2Dev/nonebot-plugin-akinator#7]
已经启用了系统全局代理，浏览器可以正常打开网页
05-01 23:07:43 [ERROR] nonebot_plugin_akinator | 启动游戏失败
Traceback (most recent call last):
  File "D:\NoneBot\ABK\.venv\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 709, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 826, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 613, in finish_connect
    ov.getresult()
OSError: [WinError 121] 信号灯超时时间已到

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_akinator\__main__.py", line 35, in _
    await game.start_game()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_akinator\game.py", line 42, in wrapper
    return await async_func(self, *args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_akinator\game.py", line 74, in start_game
    return await super().start_game(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_akinator\akinator\akinator\async_aki\async_akinator.py", line 190, in start_game
    region_info = await self._auto_get_region(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_akinator\akinator\akinator\async_aki\async_akinator.py", line 124, in _auto_get_region
    async with self.client_session.get("https://" + uri, proxy=self.proxy, ssl=False) as w:
  File "D:\NoneBot\ABK\.venv\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\NoneBot\ABK\.venv\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\NoneBot\ABK\.venv\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host cn.akinator.com:443 ssl:False [信号灯超时时间已到]

**Comment by lgc2333** [comment]
待调查原因

**Comment by lgc2333** [comment]
貌似应该好像恢复了，还有问题请继续回复issue
